import { weirdcoreGallery } from './weirdcore-curated.js';
import { tacticalGallery } from './tactical-curated.js';

export const curatedGalleryData = {
  "weirdcore": weirdcoreGallery,
  "tactical": tacticalGallery,
  "skeuomorphism": [
    {
      "title": "TouchWiz 2012 dial pad",
      "creator": "Software: Samsung Mobile\nScreen shot: Randy from AndroidAuthority",
      "date": "2012-05-27",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2012_dial_pad.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/ca/TouchWiz_2012_dial_pad.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "拨号与通话",
      "remote": true
    },
    {
      "title": "HTC Evo 4G Main Screen",
      "creator": "closari",
      "date": "2010-05-21",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:HTC_Evo_4G_Main_Screen.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/e/e6/HTC_Evo_4G_Main_Screen.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "HTC Sense 主屏",
      "remote": true
    },
    {
      "title": "Leather Notepad",
      "creator": "TTerlizz",
      "date": "2013-08-07 01:07:00",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leather_Notepad.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Leather_Notepad.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "材质模拟",
      "remote": true
    },
    {
      "title": "TouchWiz 2013 control menu",
      "creator": "Samsung Mobile",
      "date": "2014-07-28",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2013_control_menu.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/7/78/TouchWiz_2013_control_menu.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "实体控件隐喻",
      "remote": true
    },
    {
      "title": "Android screenshot",
      "creator": "Android Developers http://developer.android.com/index.html",
      "date": "Screenshot: 7 December 2010",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_screenshot.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Android_screenshot.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Rainlendar Skins",
      "creator": "rainy",
      "date": "2005-06-09",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rainlendar_Skins.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/9/90/Rainlendar_Skins.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "桌面日历隐喻",
      "remote": true
    },
    {
      "title": "Foliate skeuomorphism",
      "creator": "John Factotum",
      "date": "2020-01-20",
      "license": "GPLv3",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Foliate_skeuomorphism.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Foliate_skeuomorphism.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "书页隐喻",
      "remote": true
    },
    {
      "title": "Korg iMonoPoly",
      "creator": "Joshua Philgarlic (Diskussion)",
      "date": "2017-10-06",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Korg_iMonoPoly.PNG",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Korg_iMonoPoly.PNG/1280px-Korg_iMonoPoly.PNG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "合成器与旋钮",
      "remote": true
    },
    {
      "title": "TouchWiz 2012 phone call",
      "creator": "Samsung Mobile",
      "date": "2013-02-21",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2012_phone_call.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/e/e3/TouchWiz_2012_phone_call.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "拨号与通话",
      "remote": true
    },
    {
      "title": "TouchWiz 2013 controls horizontal",
      "creator": "Samsung Mobile",
      "date": "2016-01-11 16:35:19",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2013_controls_horizontal.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/TouchWiz_2013_controls_horizontal.png/1280px-TouchWiz_2013_controls_horizontal.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "实体控件隐喻",
      "remote": true
    },
    {
      "title": "TouchWiz 2013 device options",
      "creator": "Samsung Mobile",
      "date": "2012-12-19",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2013_device_options.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/a/a1/TouchWiz_2013_device_options.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "系统面板",
      "remote": true
    },
    {
      "title": "TouchWiz 2014 controls",
      "creator": "Samsung Mobile",
      "date": "2016-05-04 17:59:23",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2014_controls.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/9/9d/TouchWiz_2014_controls.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "实体控件隐喻",
      "remote": true
    },
    {
      "title": "TouchWiz phone options concept",
      "creator": "Derived by a close friend who permitted me to upload it.",
      "date": "2018-10-08",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_phone_options_concept.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/8/8a/TouchWiz_phone_options_concept.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "拨号与通话",
      "remote": true
    },
    {
      "title": "Samsung Galaxy S5 settings menu",
      "creator": "User interface created by Samsung Mobile.",
      "date": "2014-06-23",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S5_settings_menu.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/8/81/Samsung_Galaxy_S5_settings_menu.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "系统设置",
      "remote": true
    },
    {
      "title": "Apps info",
      "creator": "Wikimedia Commons contributor",
      "date": "2017-09-12",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apps_info.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Apps_info.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "系统设置",
      "remote": true
    },
    {
      "title": "Option menu - TouchWiz 2015 gallery application",
      "creator": "Samsung Mobile",
      "date": "2015",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Option_menu_-_TouchWiz_2015_gallery_application.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Option_menu_-_TouchWiz_2015_gallery_application.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "相册与菜单",
      "remote": true
    },
    {
      "title": "Option menu (2) - TouchWiz 2015 gallery application",
      "creator": "Samsung Mobile",
      "date": "2015",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Option_menu_(2)_-_TouchWiz_2015_gallery_application.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/7/76/Option_menu_%282%29_-_TouchWiz_2015_gallery_application.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "相册与菜单",
      "remote": true
    },
    {
      "title": "Text selection magnification",
      "creator": "Samsung Mobile",
      "date": "2015",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_magnification.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Text_selection_magnification.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "放大镜隐喻",
      "remote": true
    },
    {
      "title": "Text selection context menu with icons - TouchWiz 2013",
      "creator": "Samsung Mobile",
      "date": "2013",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_context_menu_with_icons_-_TouchWiz_2013.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/7/74/Text_selection_context_menu_with_icons_-_TouchWiz_2013.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "Text selection context menu - side scroll - TouchWiz 2013",
      "creator": "Samsung Mobile",
      "date": "2013",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_context_menu_-_side_scroll_-_TouchWiz_2013.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/1/18/Text_selection_context_menu_-_side_scroll_-_TouchWiz_2013.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "Text selection context menu - side scroll (2) - TouchWiz 2013",
      "creator": "Samsung Mobile",
      "date": "2013",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_context_menu_-_side_scroll_(2)_-_TouchWiz_2013.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/da/Text_selection_context_menu_-_side_scroll_%282%29_-_TouchWiz_2013.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "Text selection context menu - side scroll (3) - TouchWiz 2013",
      "creator": "Samsung Mobile",
      "date": "2013",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_context_menu_-_side_scroll_(3)_-_TouchWiz_2013.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Text_selection_context_menu_-_side_scroll_%283%29_-_TouchWiz_2013.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "TouchWiz 2014 blurred transclucent notification menu concept",
      "creator": "Derived work by close friend of mine, who permitted me to upload it.",
      "date": "2018-08-24",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:TouchWiz_2014_blurred_transclucent_notification_menu_concept.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/c5/TouchWiz_2014_blurred_transclucent_notification_menu_concept.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "系统面板",
      "remote": true
    },
    {
      "title": "Text selection menu with icons - input field - TouchWiz 2015",
      "creator": "Samsung Mobile and SoundCloud",
      "date": "2022-09-03",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_menu_with_icons_-_input_field_-_TouchWiz_2015.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Text_selection_menu_with_icons_-_input_field_-_TouchWiz_2015.png/1280px-Text_selection_menu_with_icons_-_input_field_-_TouchWiz_2015.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "Text selection menu with icons - plain text - TouchWiz 2015",
      "creator": "Samsung Mobile, Wikipedia",
      "date": "2022-09-21",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Text_selection_menu_with_icons_-_plain_text_-_TouchWiz_2015.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Text_selection_menu_with_icons_-_plain_text_-_TouchWiz_2015.png/1280px-Text_selection_menu_with_icons_-_plain_text_-_TouchWiz_2015.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "上下文菜单",
      "remote": true
    },
    {
      "title": "Android-2.3",
      "creator": "Android Developers http://developer.android.com/index.html",
      "date": "2010-12-06",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android-2.3.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Android-2.3.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android OS, v2.3 (Gingerbread)",
      "creator": "User:Faramarz",
      "date": "Screenshot: 7 February 2012",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_OS,_v2.3_(Gingerbread).png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Android_OS%2C_v2.3_%28Gingerbread%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android 2.2 Froyo home",
      "creator": "LR Guanzon",
      "date": "21 May 2014 (according to Exif data)",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_2.2_Froyo_home.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Android_2.2_Froyo_home.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android Froyo 2.2",
      "creator": "AdonisEuropeo",
      "date": "2014-10-22 21:34:49",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_Froyo_2.2.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/6/61/Android_Froyo_2.2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android-2.2",
      "creator": "Android Developers http://developer.android.com/index.html",
      "date": "2010-05-20",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android-2.2.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Android-2.2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Nexus one home screen 21",
      "creator": "Google LLC, AOSP",
      "date": "2010-05-12 02:05:00",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nexus_one_home_screen_21.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/df/Nexus_one_home_screen_21.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android 2.1 Screenshot",
      "creator": "The Android Open Source Project",
      "date": "2011-10-16",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_2.1_Screenshot.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Android_2.1_Screenshot.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android 1.6 on the Android SDK",
      "creator": "The Android Open Source Project",
      "date": "2017-10-31 05:26:09",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_1.6_on_the_Android_SDK.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Android_1.6_on_the_Android_SDK.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android Donut homescreen",
      "creator": "Hajoon0102",
      "date": "2021-09-06",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_Donut_homescreen.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Android_Donut_homescreen.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "Android-1.6",
      "creator": "mrphelpls",
      "date": "2014-03-12",
      "license": "Apache License 2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android-1.6.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Android-1.6.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "早期 Android 主屏",
      "remote": true
    },
    {
      "title": "LG Optimus L3 E400 display",
      "creator": "АндрейХьюстон",
      "date": "2013-02-16 13:11:46",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:LG_Optimus_L3_E400_display.JPG",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/LG_Optimus_L3_E400_display.JPG/1280px-LG_Optimus_L3_E400_display.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "厂商定制主屏",
      "remote": true
    },
    {
      "title": "Sony Xperia S Home Screen Chinese version 120421",
      "creator": "Novo8",
      "date": "2012-04-21",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sony_Xperia_S_Home_Screen_Chinese_version_120421.JPG",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Sony_Xperia_S_Home_Screen_Chinese_version_120421.JPG/1280px-Sony_Xperia_S_Home_Screen_Chinese_version_120421.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "厂商定制主屏",
      "remote": true
    },
    {
      "title": "Sony Ericsson Xperia arc S 20120421",
      "creator": "Novo8",
      "date": "2012-04-21",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sony_Ericsson_Xperia_arc_S_20120421.JPG",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sony_Ericsson_Xperia_arc_S_20120421.JPG/1280px-Sony_Ericsson_Xperia_arc_S_20120421.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "厂商定制主屏",
      "remote": true
    },
    {
      "title": "Sony Ericsson Xperia mini pro 20120421",
      "creator": "Novo8",
      "date": "2012-04-21",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sony_Ericsson_Xperia_mini_pro_20120421.JPG",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Sony_Ericsson_Xperia_mini_pro_20120421.JPG/1280px-Sony_Ericsson_Xperia_mini_pro_20120421.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "厂商定制主屏",
      "remote": true
    },
    {
      "title": "Android 2.2 GT-I5800",
      "creator": "Crusier and Android Developers http://developer.android.com/index.html",
      "date": "2011-05-07",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Android_2.2_GT-I5800.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Android_2.2_GT-I5800.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "厂商定制主屏",
      "remote": true
    },
    {
      "title": "Division by zero on android 2.2.1 calculator",
      "creator": "Eupsychos",
      "date": "2014-06-06 17:27:26",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Division_by_zero_on_android_2.2.1_calculator.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/1/16/Division_by_zero_on_android_2.2.1_calculator.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "计算器隐喻",
      "remote": true
    },
    {
      "title": "Nrosegarden+qsynth+jack+hexterdx7",
      "creator": "No machine-readable author provided. MarcosManoni~commonswiki assumed (based on copyright claims).",
      "date": "16 February 2006 (original upload date)",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nrosegarden%2Bqsynth%2Bjack%2Bhexterdx7.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Nrosegarden%2Bqsynth%2Bjack%2Bhexterdx7.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "合成器与旋钮",
      "remote": true
    },
    {
      "title": "Zyn-Fusion",
      "creator": "Tempo Flugas",
      "date": "2019-06-07",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zyn-Fusion.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zyn-Fusion.png/1280px-Zyn-Fusion.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "合成器与旋钮",
      "remote": true
    },
    {
      "title": "Trance Gate Section - PoiZone V2",
      "creator": "Franz Daniel Valsky",
      "date": "2026-02-08",
      "license": "CC0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trance_Gate_Section_-_PoiZone_V2.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Trance_Gate_Section_-_PoiZone_V2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "音频设备隐喻",
      "remote": true
    },
    {
      "title": "Automix 4 graphic user interface",
      "creator": "Binksternet",
      "date": "2008-10-06",
      "license": "Public domain",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Automix_4_graphic_user_interface.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/9/94/Automix_4_graphic_user_interface.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "调音台隐喻",
      "remote": true
    },
    {
      "title": "Alsa Modular Synth 2.1.2",
      "creator": "EP111",
      "date": "2020-11-29",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alsa_Modular_Synth_2.1.2.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Alsa_Modular_Synth_2.1.2.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "模块化合成器",
      "remote": true
    },
    {
      "title": "Hyper Canvas and TTS-1",
      "creator": "Julthep",
      "date": "2022-10-18",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyper_Canvas_and_TTS-1.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Hyper_Canvas_and_TTS-1.png/1280px-Hyper_Canvas_and_TTS-1.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
      "subject": "音源机架隐喻",
      "remote": true
    },
    {
      "title": "CCI200 Terminal",
      "creator": "Competence Center ISOBUS e.V.",
      "date": "2010-03-17",
      "license": "CC BY-SA 3.0 de",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:CCI200_Terminal.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/f/f7/CCI200_Terminal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "实体终端隐喻",
      "remote": true
    },
    {
      "title": "Qalculate-gtk",
      "creator": "User:Sir_Link",
      "date": "2007-02-18",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Qalculate-gtk.png",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/5/56/Qalculate-gtk.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "计算器隐喻",
      "remote": true
    },
    {
      "title": "Zimbra calendar",
      "creator": "Wikimedia Commons contributor",
      "date": "2007-03-18 17:42:19",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Zimbra_calendar.jpg",
      "provider": "Wikimedia Commons",
      "src": "https://upload.wikimedia.org/wikipedia/commons/2/23/Zimbra_calendar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
      "subject": "桌面日历隐喻",
      "remote": true
    }
  ]
};
